name: Rust documentation 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  CARGO_TERM_COLOR: always
  
permissions:
  contents: write
  deployments: write

jobs:
  documentation:
    name: Documentation generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain update nightly && rustup default nightly
      - name: run doc generation 
        run: |
          cargo doc --no-deps
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          mkdir repo_clone
          git clone --single-branch --branch gh-pages "https://${{ secrets.GITHUB_TOKEN }}@github.com/melcar/cmprsd.git" repo_clone
          rsync -r target/doc/ ./repo_clone
          cd repo_clone
          if [ -n "$(git diff --exit-code)" ];then 
            git add ./doc/*
            git commit ./doc/* -m "doc generated"
            git push "https://${{ secrets.PAT }}@github.com/melcar/cmprsd.git"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_PAT: ${{ secrets.PAT }} 